### ISSUE TITLE
Add optional JSON revision parameter to the Get Command Output keyword

### ISSUE THREAD

**Issue by ksantos01** [aristanetworks/robotframework-aristalibrary#21]
JSON output of some commands has multiple revisions number. By default, the JSON output on the CLI uses the highest revision while the CAPI the lowest unless specified otherwise. The possibility to specify the revision number in the **Get Command Output** keyword will become useful when you want to get the revision 2/3 of a show command.

**Comment by jerearista** [comment]
Requires arista-eosplus/pyeapi#158 in v0.8.2.
